# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
    downloadUrl: 'https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_386.zip'

- task: TerraformCLI@0
  inputs:
    command: 'validate'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'plan'
    allowTelemetryCollection: true

